### ISSUE TITLE
Can't login to Spotify after upgrade to Ubuntu 12.04

### ISSUE THREAD

**Issue by skeenan** [jodal/pyspotify#65]
After upgrading ubuntu to 12.04 mopidy will no longer start.

using mopidy 0.7.2, pyspotify 1.7.

```
$ python -c "import spotify; print (spotify.__version__, spotify.__file__)"
('1.7', '/usr/lib/python2.7/dist-packages/spotify/__init__.pyc')
```

Mopidy log:

```
INFO     Starting Mopidy 0.7.2 on Linux-3.2.0-24-generic-i686-with-Ubuntu-12.04-precise CPython 2.7.3
INFO     Mopidy uses SPOTIFY(R) CORE
ERROR    No credentials stored
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/process.py", line 53, in run
    self.run_inside_try()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/backends/spotify/session_manager.py", line 47, in run_inside_try
    self.connect()
  File "/usr/lib/python2.7/dist-packages/spotify/manager/session.py", line 53, in connect
    session = spotify.connect(self)
SpotifyError: No credentials stored
INFO     MPD server running at [::ffff:0.0.0.0]:6600
INFO     Last.fm scrobbler not started
ImportError: could not import gtk.gdk
INFO     Connected to D-Bus
ERROR    MPRIS frontend setup failed ('module' object has no attribute 'Server')
```
